web/router.ex
defmodule StubOnWeb.Router do
  use StubOnWeb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StubOnWeb do
    pipe_through :browser # Use the default browser stack

    get "/", StubUrlController, :new
    get "/new", StubUrlController, :new
    get "/new/:template", StubUrlController, :new
    resources "/stub_urls", StubUrlController, only: [:new, :create, :update]
    get "/edit/*path_fragments", StubUrlController, :edit
    get "/calls/*path_fragments", StubUrlController, :show_calls
  end


  scope "/", StubOnWeb do
    # TODO: Figure out one liner to add below routes
    get "/*path_fragments", StubUrlController, :show
    post "/*path_fragments", StubUrlController, :show
    put "/*path_fragments", StubUrlController, :show
    delete "/*path_fragments", StubUrlController, :show
    head "/*path_fragments", StubUrlController, :show
    patch "/*path_fragments", StubUrlController, :show
    options "/*path_fragments", StubUrlController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", StubOnWeb do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule StubOnWeb.LayoutView do
  use StubOnWeb.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>StubOnWeb</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <a target="_new" href="https://github.com/endeepak/stub_on_web" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#428bca; color:#fff; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">StubOnWeb (Beta)</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="<%= stub_url_url(@conn, :new) %>">Add New</a></li>
          </ul>
          <form class="navbar-form navbar-left" role="create">
            <div class="btn-group">
              <a href="/new/json" class="btn btn-default">JSON</a>
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="/new/xml">XML</a></li>
                <li><a href="/new/html">HTML</a></li>
              </ul>
            </div>
          </form>
          <form class="navbar-form navbar-left stub-url-action-form" role="search">
            <div class="form-group">
              <input id="stub-url-search" type="text" class="form-control" placeholder="Enter existing stub url or path" required>
            </div>
            <button type="submit" name="stub-url-action" value="calls" class="btn btn-default">Show Calls</button>
            <button type="submit" name="stub-url-action" value="edit" class="btn btn-default">Edit</button>
          </form>
        </div>
      </div>
    </nav>      
    <div id="main-content" class="container" role="main">
      <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

    </div> <!-- /container -->
    <footer class="footer">
      Created by <a href="https://github.com/endeepak" target="_blank">endeepak</a>
    </footer>
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>